Update from master (#41)
*  Convert UTF-16 encoded files to UTF-8 to fix compilation issues on MacOS

* Introduce a search bar in the scene graph (#26)

* Fullscreen is enabled only when CTRL is activated (#27)

* enable fullscreen key only if ctrl is enabled as well

* update readme

* Format some Data (#22)

* Imgui: Use OpenGL2 mode for macOS (#25)

* Force ogl2 for mac with imgui

* fix cmake when set-force option

* fix preprocessor var name and test

Co-authored-by: Frédérick ROY <fred.roy.mr@gmail.com>

* Add option to enable MSAA (#28)

* Force ogl2 for mac with imgui

* fix cmake when set-force option

* fix preprocessor var name and test

* Introduce a search bar in the scene graph (#26)

* add optional parameter to enable msaa (multisampling antialiasing)

* Explicit acronym

Co-authored-by: Frédérick ROY <fred.roy.mr@gmail.com>
Co-authored-by: Alex Bilger <alxbilger@users.noreply.github.com>
Co-authored-by: Alex Bilger <alexbilger0@gmail.com>

* Format RigidCoord types (#29)

* Format RigidCoord types

* Rename quaternion headers

* Request disabling Vsync (#30)

* Split SofaGLFW and introduce SofaImGui plugin (#32)

* split

* update config and fix move

* make glfw a shared lib

* rename sofaglfw plugin with its name

Co-authored-by: Frédérick ROY <fred.roy.mr@gmail.com>

* Icon colors in the scene graph (#33)

* Wrap Data description

* Show color depending on object type

* Change icon and color if messages

* Restore mouse behavior (#35)

3d interaction with the mouse is possible only when not interacting with a 2d UI widget

* Remove unused file (#36)

* Capture logs (#34)

* Viewport (#37)

* Introduce window for a 3d viewport

* Render scene in a viewport

* Add per-component messages tab (#38)

* Remove need of the (soon-to-be deprecated) module SofaBase (#31)

* Show Data links and open window on click (#39)

* Activate compilation SofaImGui

* Minimal reorganization of the ImGui code (#40)

* Show Data links and open window on click

* Minimal reorganization of the ImGui code

Each window has its own member function

Co-authored-by: Frederick Roy <fredroy@users.noreply.github.com>

* Fix compilation (#42)

* Show object name in log (#43)

* Show object name in log

* Show path

* Fix undefined reference to dlopen (#45)

* Clean cmake (#47)

* Fix CMake error Cannot determine link language for target nfd

* Clean cmake

* Sofa.SimulationCore replaced by Sofa.Simulation.Core

* Fix include

* Fix include

* Fix targets

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* make it compile wo compat and fix compilation (missing include)

* use the integrated mechanism to get the info about having sofa.gui.common

* fix support for building sofaimgui out-of-tree (in the same project as sofaglfw)

Co-authored-by: Frederick ROY <fred.roy.me@gmail.com>

* Install gtk on CI

Co-authored-by: Jean-Nicolas Brunet <jnbrunet2000@gmail.com>
Co-authored-by: Frederick Roy <fredroy@users.noreply.github.com>
Co-authored-by: Frédérick ROY <fred.roy.mr@gmail.com>
Co-authored-by: Frederick ROY <fred.roy.me@gmail.com>